[theme]
primaryColor = "#ff6b35"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f0f2f6"
textColor = "#262730"

[server]
headless = true
port = 8502
address = "localhost"
enableCORS = true
enableXsrfProtection = false

[browser]
gatherUsageStats = false